In [1]:
import tensorflow as tf
width  = tf.placeholder("int32", name='width')
height = tf.placeholder("int32", name='height')
area   = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area =', sess.run(area, feed_dict={width: 6, height: 8}))

area = 48


In [2]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

In [3]:
ts_X = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [4]:
print(X.shape)

(3,)


In [5]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [6]:
print('shape:', X.shape)

shape: (1, 3)


In [7]:
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_ary = sess.run(W)
    print(W_ary)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [8]:
print('shape:', W_ary.shape)

shape: (3, 2)


In [9]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])

XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


In [10]:
b  = tf.Variable([[ 0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = XW + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:', sess.run(Sum))

Sum: [[-1.1999999  0.6      ]]


In [11]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])

b  = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X, W) + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
